feat: hugo init
KochiFOSS/kochifoss.github.io pull request #4
Opened 2024-10-30 09:21 UTC by VishnuSanal

this PR contains the implementation of the current design using hugo & initialization of CI for auto deployments.

someone with admins access: please select source => github actions under build & deployment section from settings => pages (https://github.com/KochiFOSS/kochifoss.github.io/settings/pages)

2024-10-30 11:00 UTC, VishnuSanal commented
live deployment: https://vishnusanal.github.io/kochifoss.github.io/

2024-10-31 07:29 UTC, subins2000 approved these changes

2024-10-31 07:30 UTC, subins2000 requested changes
@VishnuSanal _a One change needed, LGTM

2024-10-31 07:30 UTC, subins2000 commented on .hugo_build.lock
This file should be in `.gitignore`

2024-10-31 07:35 UTC, merged

2024-10-31 07:39 UTC, subins2000 commented
Awesome, the site on Hugo is now up :rocket: https://kochifoss.org/ Thanks @VishnuSanal !