feat: timeline init
KochiFOSS/kochifoss.github.io pull request #6
Opened 2024-11-16 03:46 UTC by VishnuSanal

2024-11-16 04:10 UTC, VishnuSanal commented
preview: https://vishnusanal.github.io/kochifoss.github.io/

2024-11-16 17:32 UTC, RiyaMathew-11 commented
@VishnuSanal - maybe let's keep the homepage short with the highlight of the upcoming meetup, and bring the timeline to another page? - we do have to fill it up with all the meetups since now too.

2024-11-17 06:40 UTC, subins2000 requested changes
@VishnuSanal

2024-11-17 06:40 UTC, subins2000 commented on themes/timeline/i18n/pt-br.toml
> +[translations]
en, ml മതി. ബാക്കി ഭാഷയൊന്നും വേണ്ടാ

2024-11-17 06:40 UTC, subins2000 commented on .hugo_build.lock
This file should be gitignored

2024-11-17 06:40 UTC, subins2000 commented on resources/_gen/assets/scss/main.scss_8f107e2e3689beeb47e911c025a030db.json
> +{"Target":"main.a35ab810654226b5a9aef700df8a3758ebfc89c4c14ab5186eff55e2c08ae43e.css","MediaType":"text/css","Data":{"Integrity":"sha256-o1q4EGVCJrWprvcA34o3WOv8icTBSrUYbv9V4sCK5D4="}}
I believe this should be gitignored too

2024-11-17 06:40 UTC, subins2000 commented on themes/timeline/README.md
> +# hugo-theme-timeline
I see there are a lot of things that come with the theme, many css, fonts, language files. Can we keep the current homepage https://kochifoss.org as it is and only extract just the timeline?

i.e a new theme that keeps the current styling and just extracted timeline of the timeline theme

2024-11-21 15:16 UTC, VishnuSanal commented
superseded by #7

2024-11-21 15:16 UTC, closed without merging